---
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      day: sunday
      interval: weekly
    labels:
      - dependabot-deps-updates
      - skip-changelog
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "skip-changelog"
