---
name: release

on:
  release:
    types: [published]

jobs:
  publish-to-testpypi:
    name: Publish ansible-creator 🛠️ package 📦 to TestPyPI
    if: github.event_name == 'release'
    environment: release
    runs-on: ubuntu-22.04
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Switch to using Python 3.9 by default
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install build
        run: >-
          python3 -m
          pip install
          --user
          build

      - name: Check out src from Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed by setuptools-scm

      - name: Build dists
        run: python -m build

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Publish to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
